declare const types: {
    readonly "application/andrew-inset": ["ez"];
    readonly "application/appinstaller": ["appinstaller"];
    readonly "application/applixware": ["aw"];
    readonly "application/appx": ["appx"];
    readonly "application/appxbundle": ["appxbundle"];
    readonly "application/atom+xml": ["atom"];
    readonly "application/atomcat+xml": ["atomcat"];
    readonly "application/atomdeleted+xml": ["atomdeleted"];
    readonly "application/atomsvc+xml": ["atomsvc"];
    readonly "application/atsc-dwd+xml": ["dwd"];
    readonly "application/atsc-held+xml": ["held"];
    readonly "application/atsc-rsat+xml": ["rsat"];
    readonly "application/automationml-aml+xml": ["aml"];
    readonly "application/automationml-amlx+zip": ["amlx"];
    readonly "application/bdoc": ["bdoc"];
    readonly "application/calendar+xml": ["xcs"];
    readonly "application/ccxml+xml": ["ccxml"];
    readonly "application/cdfx+xml": ["cdfx"];
    readonly "application/cdmi-capability": ["cdmia"];
    readonly "application/cdmi-container": ["cdmic"];
    readonly "application/cdmi-domain": ["cdmid"];
    readonly "application/cdmi-object": ["cdmio"];
    readonly "application/cdmi-queue": ["cdmiq"];
    readonly "application/cpl+xml": ["cpl"];
    readonly "application/cu-seeme": ["cu"];
    readonly "application/cwl": ["cwl"];
    readonly "application/dash+xml": ["mpd"];
    readonly "application/dash-patch+xml": ["mpp"];
    readonly "application/davmount+xml": ["davmount"];
    readonly "application/dicom": ["dcm"];
    readonly "application/docbook+xml": ["dbk"];
    readonly "application/dssc+der": ["dssc"];
    readonly "application/dssc+xml": ["xdssc"];
    readonly "application/ecmascript": ["ecma"];
    readonly "application/emma+xml": ["emma"];
    readonly "application/emotionml+xml": ["emotionml"];
    readonly "application/epub+zip": ["epub"];
    readonly "application/exi": ["exi"];
    readonly "application/express": ["exp"];
    readonly "application/fdf": ["fdf"];
    readonly "application/fdt+xml": ["fdt"];
    readonly "application/font-tdpfr": ["pfr"];
    readonly "application/geo+json": ["geojson"];
    readonly "application/gml+xml": ["gml"];
    readonly "application/gpx+xml": ["gpx"];
    readonly "application/gxf": ["gxf"];
    readonly "application/gzip": ["gz"];
    readonly "application/hjson": ["hjson"];
    readonly "application/hyperstudio": ["stk"];
    readonly "application/inkml+xml": ["ink", "inkml"];
    readonly "application/ipfix": ["ipfix"];
    readonly "application/its+xml": ["its"];
    readonly "application/java-archive": ["jar", "war", "ear"];
    readonly "application/java-serialized-object": ["ser"];
    readonly "application/java-vm": ["class"];
    readonly "application/javascript": ["*js"];
    readonly "application/json": ["json", "map"];
    readonly "application/json5": ["json5"];
    readonly "application/jsonml+json": ["jsonml"];
    readonly "application/ld+json": ["jsonld"];
    readonly "application/lgr+xml": ["lgr"];
    readonly "application/lost+xml": ["lostxml"];
    readonly "application/mac-binhex40": ["hqx"];
    readonly "application/mac-compactpro": ["cpt"];
    readonly "application/mads+xml": ["mads"];
    readonly "application/manifest+json": ["webmanifest"];
    readonly "application/marc": ["mrc"];
    readonly "application/marcxml+xml": ["mrcx"];
    readonly "application/mathematica": ["ma", "nb", "mb"];
    readonly "application/mathml+xml": ["mathml"];
    readonly "application/mbox": ["mbox"];
    readonly "application/media-policy-dataset+xml": ["mpf"];
    readonly "application/mediaservercontrol+xml": ["mscml"];
    readonly "application/metalink+xml": ["metalink"];
    readonly "application/metalink4+xml": ["meta4"];
    readonly "application/mets+xml": ["mets"];
    readonly "application/mmt-aei+xml": ["maei"];
    readonly "application/mmt-usd+xml": ["musd"];
    readonly "application/mods+xml": ["mods"];
    readonly "application/mp21": ["m21", "mp21"];
    readonly "application/mp4": ["*mp4", "*mpg4", "mp4s", "m4p"];
    readonly "application/msix": ["msix"];
    readonly "application/msixbundle": ["msixbundle"];
    readonly "application/msword": ["doc", "dot"];
    readonly "application/mxf": ["mxf"];
    readonly "application/n-quads": ["nq"];
    readonly "application/n-triples": ["nt"];
    readonly "application/node": ["cjs"];
    readonly "application/octet-stream": ["bin", "dms", "lrf", "mar", "so", "dist", "distz", "pkg", "bpk", "dump", "elc", "deploy", "exe", "dll", "deb", "dmg", "iso", "img", "msi", "msp", "msm", "buffer"];
    readonly "application/oda": ["oda"];
    readonly "application/oebps-package+xml": ["opf"];
    readonly "application/ogg": ["ogx"];
    readonly "application/omdoc+xml": ["omdoc"];
    readonly "application/onenote": ["onetoc", "onetoc2", "onetmp", "onepkg", "one", "onea"];
    readonly "application/oxps": ["oxps"];
    readonly "application/p2p-overlay+xml": ["relo"];
    readonly "application/patch-ops-error+xml": ["xer"];
    readonly "application/pdf": ["pdf"];
    readonly "application/pgp-encrypted": ["pgp"];
    readonly "application/pgp-keys": ["asc"];
    readonly "application/pgp-signature": ["sig", "*asc"];
    readonly "application/pics-rules": ["prf"];
    readonly "application/pkcs10": ["p10"];
    readonly "application/pkcs7-mime": ["p7m", "p7c"];
    readonly "application/pkcs7-signature": ["p7s"];
    readonly "application/pkcs8": ["p8"];
    readonly "application/pkix-attr-cert": ["ac"];
    readonly "application/pkix-cert": ["cer"];
    readonly "application/pkix-crl": ["crl"];
    readonly "application/pkix-pkipath": ["pkipath"];
    readonly "application/pkixcmp": ["pki"];
    readonly "application/pls+xml": ["pls"];
    readonly "application/postscript": ["ai", "eps", "ps"];
    readonly "application/provenance+xml": ["provx"];
    readonly "application/pskc+xml": ["pskcxml"];
    readonly "application/raml+yaml": ["raml"];
    readonly "application/rdf+xml": ["rdf", "owl"];
    readonly "application/reginfo+xml": ["rif"];
    readonly "application/relax-ng-compact-syntax": ["rnc"];
    readonly "application/resource-lists+xml": ["rl"];
    readonly "application/resource-lists-diff+xml": ["rld"];
    readonly "application/rls-services+xml": ["rs"];
    readonly "application/route-apd+xml": ["rapd"];
    readonly "application/route-s-tsid+xml": ["sls"];
    readonly "application/route-usd+xml": ["rusd"];
    readonly "application/rpki-ghostbusters": ["gbr"];
    readonly "application/rpki-manifest": ["mft"];
    readonly "application/rpki-roa": ["roa"];
    readonly "application/rsd+xml": ["rsd"];
    readonly "application/rss+xml": ["rss"];
    readonly "application/rtf": ["rtf"];
    readonly "application/sbml+xml": ["sbml"];
    readonly "application/scvp-cv-request": ["scq"];
    readonly "application/scvp-cv-response": ["scs"];
    readonly "application/scvp-vp-request": ["spq"];
    readonly "application/scvp-vp-response": ["spp"];
    readonly "application/sdp": ["sdp"];
    readonly "application/senml+xml": ["senmlx"];
    readonly "application/sensml+xml": ["sensmlx"];
    readonly "application/set-payment-initiation": ["setpay"];
    readonly "application/set-registration-initiation": ["setreg"];
    readonly "application/shf+xml": ["shf"];
    readonly "application/sieve": ["siv", "sieve"];
    readonly "application/smil+xml": ["smi", "smil"];
    readonly "application/sparql-query": ["rq"];
    readonly "application/sparql-results+xml": ["srx"];
    readonly "application/sql": ["sql"];
    readonly "application/srgs": ["gram"];
    readonly "application/srgs+xml": ["grxml"];
    readonly "application/sru+xml": ["sru"];
    readonly "application/ssdl+xml": ["ssdl"];
    readonly "application/ssml+xml": ["ssml"];
    readonly "application/swid+xml": ["swidtag"];
    readonly "application/tei+xml": ["tei", "teicorpus"];
    readonly "application/thraud+xml": ["tfi"];
    readonly "application/timestamped-data": ["tsd"];
    readonly "application/toml": ["toml"];
    readonly "application/trig": ["trig"];
    readonly "application/ttml+xml": ["ttml"];
    readonly "application/ubjson": ["ubj"];
    readonly "application/urc-ressheet+xml": ["rsheet"];
    readonly "application/urc-targetdesc+xml": ["td"];
    readonly "application/voicexml+xml": ["vxml"];
    readonly "application/wasm": ["wasm"];
    readonly "application/watcherinfo+xml": ["wif"];
    readonly "application/widget": ["wgt"];
    readonly "application/winhlp": ["hlp"];
    readonly "application/wsdl+xml": ["wsdl"];
    readonly "application/wspolicy+xml": ["wspolicy"];
    readonly "application/xaml+xml": ["xaml"];
    readonly "application/xcap-att+xml": ["xav"];
    readonly "application/xcap-caps+xml": ["xca"];
    readonly "application/xcap-diff+xml": ["xdf"];
    readonly "application/xcap-el+xml": ["xel"];
    readonly "application/xcap-ns+xml": ["xns"];
    readonly "application/xenc+xml": ["xenc"];
    readonly "application/xfdf": ["xfdf"];
    readonly "application/xhtml+xml": ["xhtml", "xht"];
    readonly "application/xliff+xml": ["xlf"];
    readonly "application/xml": ["xml", "xsl", "xsd", "rng"];
    readonly "application/xml-dtd": ["dtd"];
    readonly "application/xop+xml": ["xop"];
    readonly "application/xproc+xml": ["xpl"];
    readonly "application/xslt+xml": ["*xsl", "xslt"];
    readonly "application/xspf+xml": ["xspf"];
    readonly "application/xv+xml": ["mxml", "xhvml", "xvml", "xvm"];
    readonly "application/yang": ["yang"];
    readonly "application/yin+xml": ["yin"];
    readonly "application/zip": ["zip"];
    readonly "application/zip+dotlottie": ["lottie"];
    readonly "audio/3gpp": ["*3gpp"];
    readonly "audio/aac": ["adts", "aac"];
    readonly "audio/adpcm": ["adp"];
    readonly "audio/amr": ["amr"];
    readonly "audio/basic": ["au", "snd"];
    readonly "audio/midi": ["mid", "midi", "kar", "rmi"];
    readonly "audio/mobile-xmf": ["mxmf"];
    readonly "audio/mp3": ["*mp3"];
    readonly "audio/mp4": ["m4a", "mp4a", "m4b"];
    readonly "audio/mpeg": ["mpga", "mp2", "mp2a", "mp3", "m2a", "m3a"];
    readonly "audio/ogg": ["oga", "ogg", "spx", "opus"];
    readonly "audio/s3m": ["s3m"];
    readonly "audio/silk": ["sil"];
    readonly "audio/wav": ["wav"];
    readonly "audio/wave": ["*wav"];
    readonly "audio/webm": ["weba"];
    readonly "audio/xm": ["xm"];
    readonly "font/collection": ["ttc"];
    readonly "font/otf": ["otf"];
    readonly "font/ttf": ["ttf"];
    readonly "font/woff": ["woff"];
    readonly "font/woff2": ["woff2"];
    readonly "image/aces": ["exr"];
    readonly "image/apng": ["apng"];
    readonly "image/avci": ["avci"];
    readonly "image/avcs": ["avcs"];
    readonly "image/avif": ["avif"];
    readonly "image/bmp": ["bmp", "dib"];
    readonly "image/cgm": ["cgm"];
    readonly "image/dicom-rle": ["drle"];
    readonly "image/dpx": ["dpx"];
    readonly "image/emf": ["emf"];
    readonly "image/fits": ["fits"];
    readonly "image/g3fax": ["g3"];
    readonly "image/gif": ["gif"];
    readonly "image/heic": ["heic"];
    readonly "image/heic-sequence": ["heics"];
    readonly "image/heif": ["heif"];
    readonly "image/heif-sequence": ["heifs"];
    readonly "image/hej2k": ["hej2"];
    readonly "image/ief": ["ief"];
    readonly "image/jaii": ["jaii"];
    readonly "image/jais": ["jais"];
    readonly "image/jls": ["jls"];
    readonly "image/jp2": ["jp2", "jpg2"];
    readonly "image/jpeg": ["jpg", "jpeg", "jpe"];
    readonly "image/jph": ["jph"];
    readonly "image/jphc": ["jhc"];
    readonly "image/jpm": ["jpm", "jpgm"];
    readonly "image/jpx": ["jpx", "jpf"];
    readonly "image/jxl": ["jxl"];
    readonly "image/jxr": ["jxr"];
    readonly "image/jxra": ["jxra"];
    readonly "image/jxrs": ["jxrs"];
    readonly "image/jxs": ["jxs"];
    readonly "image/jxsc": ["jxsc"];
    readonly "image/jxsi": ["jxsi"];
    readonly "image/jxss": ["jxss"];
    readonly "image/ktx": ["ktx"];
    readonly "image/ktx2": ["ktx2"];
    readonly "image/pjpeg": ["jfif"];
    readonly "image/png": ["png"];
    readonly "image/sgi": ["sgi"];
    readonly "image/svg+xml": ["svg", "svgz"];
    readonly "image/t38": ["t38"];
    readonly "image/tiff": ["tif", "tiff"];
    readonly "image/tiff-fx": ["tfx"];
    readonly "image/webp": ["webp"];
    readonly "image/wmf": ["wmf"];
    readonly "message/disposition-notification": ["disposition-notification"];
    readonly "message/global": ["u8msg"];
    readonly "message/global-delivery-status": ["u8dsn"];
    readonly "message/global-disposition-notification": ["u8mdn"];
    readonly "message/global-headers": ["u8hdr"];
    readonly "message/rfc822": ["eml", "mime", "mht", "mhtml"];
    readonly "model/3mf": ["3mf"];
    readonly "model/gltf+json": ["gltf"];
    readonly "model/gltf-binary": ["glb"];
    readonly "model/iges": ["igs", "iges"];
    readonly "model/jt": ["jt"];
    readonly "model/mesh": ["msh", "mesh", "silo"];
    readonly "model/mtl": ["mtl"];
    readonly "model/obj": ["obj"];
    readonly "model/prc": ["prc"];
    readonly "model/step": ["step", "stp", "stpnc", "p21", "210"];
    readonly "model/step+xml": ["stpx"];
    readonly "model/step+zip": ["stpz"];
    readonly "model/step-xml+zip": ["stpxz"];
    readonly "model/stl": ["stl"];
    readonly "model/u3d": ["u3d"];
    readonly "model/vrml": ["wrl", "vrml"];
    readonly "model/x3d+binary": ["*x3db", "x3dbz"];
    readonly "model/x3d+fastinfoset": ["x3db"];
    readonly "model/x3d+vrml": ["*x3dv", "x3dvz"];
    readonly "model/x3d+xml": ["x3d", "x3dz"];
    readonly "model/x3d-vrml": ["x3dv"];
    readonly "text/cache-manifest": ["appcache", "manifest"];
    readonly "text/calendar": ["ics", "ifb"];
    readonly "text/coffeescript": ["coffee", "litcoffee"];
    readonly "text/css": ["css"];
    readonly "text/csv": ["csv"];
    readonly "text/html": ["html", "htm", "shtml"];
    readonly "text/jade": ["jade"];
    readonly "text/javascript": ["js", "mjs"];
    readonly "text/jsx": ["jsx"];
    readonly "text/less": ["less"];
    readonly "text/markdown": ["md", "markdown"];
    readonly "text/mathml": ["mml"];
    readonly "text/mdx": ["mdx"];
    readonly "text/n3": ["n3"];
    readonly "text/plain": ["txt", "text", "conf", "def", "list", "log", "in", "ini"];
    readonly "text/richtext": ["rtx"];
    readonly "text/rtf": ["*rtf"];
    readonly "text/sgml": ["sgml", "sgm"];
    readonly "text/shex": ["shex"];
    readonly "text/slim": ["slim", "slm"];
    readonly "text/spdx": ["spdx"];
    readonly "text/stylus": ["stylus", "styl"];
    readonly "text/tab-separated-values": ["tsv"];
    readonly "text/troff": ["t", "tr", "roff", "man", "me", "ms"];
    readonly "text/turtle": ["ttl"];
    readonly "text/uri-list": ["uri", "uris", "urls"];
    readonly "text/vcard": ["vcard"];
    readonly "text/vtt": ["vtt"];
    readonly "text/wgsl": ["wgsl"];
    readonly "text/xml": ["*xml"];
    readonly "text/yaml": ["yaml", "yml"];
    readonly "video/3gpp": ["3gp", "3gpp"];
    readonly "video/3gpp2": ["3g2"];
    readonly "video/h261": ["h261"];
    readonly "video/h263": ["h263"];
    readonly "video/h264": ["h264"];
    readonly "video/iso.segment": ["m4s"];
    readonly "video/jpeg": ["jpgv"];
    readonly "video/jpm": ["*jpm", "*jpgm"];
    readonly "video/mj2": ["mj2", "mjp2"];
    readonly "video/mp2t": ["ts", "m2t", "m2ts", "mts"];
    readonly "video/mp4": ["mp4", "mp4v", "mpg4"];
    readonly "video/mpeg": ["mpeg", "mpg", "mpe", "m1v", "m2v"];
    readonly "video/ogg": ["ogv"];
    readonly "video/quicktime": ["qt", "mov"];
    readonly "video/webm": ["webm"];
    readonly "application/prs.cww": ["cww"];
    readonly "application/prs.xsf+xml": ["xsf"];
    readonly "application/vnd.1000minds.decision-model+xml": ["1km"];
    readonly "application/vnd.3gpp.pic-bw-large": ["plb"];
    readonly "application/vnd.3gpp.pic-bw-small": ["psb"];
    readonly "application/vnd.3gpp.pic-bw-var": ["pvb"];
    readonly "application/vnd.3gpp2.tcap": ["tcap"];
    readonly "application/vnd.3m.post-it-notes": ["pwn"];
    readonly "application/vnd.accpac.simply.aso": ["aso"];
    readonly "application/vnd.accpac.simply.imp": ["imp"];
    readonly "application/vnd.acucobol": ["acu"];
    readonly "application/vnd.acucorp": ["atc", "acutc"];
    readonly "application/vnd.adobe.air-application-installer-package+zip": ["air"];
    readonly "application/vnd.adobe.formscentral.fcdt": ["fcdt"];
    readonly "application/vnd.adobe.fxp": ["fxp", "fxpl"];
    readonly "application/vnd.adobe.xdp+xml": ["xdp"];
    readonly "application/vnd.adobe.xfdf": ["*xfdf"];
    readonly "application/vnd.age": ["age"];
    readonly "application/vnd.ahead.space": ["ahead"];
    readonly "application/vnd.airzip.filesecure.azf": ["azf"];
    readonly "application/vnd.airzip.filesecure.azs": ["azs"];
    readonly "application/vnd.amazon.ebook": ["azw"];
    readonly "application/vnd.americandynamics.acc": ["acc"];
    readonly "application/vnd.amiga.ami": ["ami"];
    readonly "application/vnd.android.package-archive": ["apk"];
    readonly "application/vnd.anser-web-certificate-issue-initiation": ["cii"];
    readonly "application/vnd.anser-web-funds-transfer-initiation": ["fti"];
    readonly "application/vnd.antix.game-component": ["atx"];
    readonly "application/vnd.apple.installer+xml": ["mpkg"];
    readonly "application/vnd.apple.keynote": ["key"];
    readonly "application/vnd.apple.mpegurl": ["m3u8"];
    readonly "application/vnd.apple.numbers": ["numbers"];
    readonly "application/vnd.apple.pages": ["pages"];
    readonly "application/vnd.apple.pkpass": ["pkpass"];
    readonly "application/vnd.aristanetworks.swi": ["swi"];
    readonly "application/vnd.astraea-software.iota": ["iota"];
    readonly "application/vnd.audiograph": ["aep"];
    readonly "application/vnd.autodesk.fbx": ["fbx"];
    readonly "application/vnd.balsamiq.bmml+xml": ["bmml"];
    readonly "application/vnd.blueice.multipass": ["mpm"];
    readonly "application/vnd.bmi": ["bmi"];
    readonly "application/vnd.businessobjects": ["rep"];
    readonly "application/vnd.chemdraw+xml": ["cdxml"];
    readonly "application/vnd.chipnuts.karaoke-mmd": ["mmd"];
    readonly "application/vnd.cinderella": ["cdy"];
    readonly "application/vnd.citationstyles.style+xml": ["csl"];
    readonly "application/vnd.claymore": ["cla"];
    readonly "application/vnd.cloanto.rp9": ["rp9"];
    readonly "application/vnd.clonk.c4group": ["c4g", "c4d", "c4f", "c4p", "c4u"];
    readonly "application/vnd.cluetrust.cartomobile-config": ["c11amc"];
    readonly "application/vnd.cluetrust.cartomobile-config-pkg": ["c11amz"];
    readonly "application/vnd.commonspace": ["csp"];
    readonly "application/vnd.contact.cmsg": ["cdbcmsg"];
    readonly "application/vnd.cosmocaller": ["cmc"];
    readonly "application/vnd.crick.clicker": ["clkx"];
    readonly "application/vnd.crick.clicker.keyboard": ["clkk"];
    readonly "application/vnd.crick.clicker.palette": ["clkp"];
    readonly "application/vnd.crick.clicker.template": ["clkt"];
    readonly "application/vnd.crick.clicker.wordbank": ["clkw"];
    readonly "application/vnd.criticaltools.wbs+xml": ["wbs"];
    readonly "application/vnd.ctc-posml": ["pml"];
    readonly "application/vnd.cups-ppd": ["ppd"];
    readonly "application/vnd.curl.car": ["car"];
    readonly "application/vnd.curl.pcurl": ["pcurl"];
    readonly "application/vnd.dart": ["dart"];
    readonly "application/vnd.data-vision.rdz": ["rdz"];
    readonly "application/vnd.dbf": ["dbf"];
    readonly "application/vnd.dcmp+xml": ["dcmp"];
    readonly "application/vnd.dece.data": ["uvf", "uvvf", "uvd", "uvvd"];
    readonly "application/vnd.dece.ttml+xml": ["uvt", "uvvt"];
    readonly "application/vnd.dece.unspecified": ["uvx", "uvvx"];
    readonly "application/vnd.dece.zip": ["uvz", "uvvz"];
    readonly "application/vnd.denovo.fcselayout-link": ["fe_launch"];
    readonly "application/vnd.dna": ["dna"];
    readonly "application/vnd.dolby.mlp": ["mlp"];
    readonly "application/vnd.dpgraph": ["dpg"];
    readonly "application/vnd.dreamfactory": ["dfac"];
    readonly "application/vnd.ds-keypoint": ["kpxx"];
    readonly "application/vnd.dvb.ait": ["ait"];
    readonly "application/vnd.dvb.service": ["svc"];
    readonly "application/vnd.dynageo": ["geo"];
    readonly "application/vnd.ecowin.chart": ["mag"];
    readonly "application/vnd.enliven": ["nml"];
    readonly "application/vnd.epson.esf": ["esf"];
    readonly "application/vnd.epson.msf": ["msf"];
    readonly "application/vnd.epson.quickanime": ["qam"];
    readonly "application/vnd.epson.salt": ["slt"];
    readonly "application/vnd.epson.ssf": ["ssf"];
    readonly "application/vnd.eszigno3+xml": ["es3", "et3"];
    readonly "application/vnd.ezpix-album": ["ez2"];
    readonly "application/vnd.ezpix-package": ["ez3"];
    readonly "application/vnd.fdf": ["*fdf"];
    readonly "application/vnd.fdsn.mseed": ["mseed"];
    readonly "application/vnd.fdsn.seed": ["seed", "dataless"];
    readonly "application/vnd.flographit": ["gph"];
    readonly "application/vnd.fluxtime.clip": ["ftc"];
    readonly "application/vnd.framemaker": ["fm", "frame", "maker", "book"];
    readonly "application/vnd.frogans.fnc": ["fnc"];
    readonly "application/vnd.frogans.ltf": ["ltf"];
    readonly "application/vnd.fsc.weblaunch": ["fsc"];
    readonly "application/vnd.fujitsu.oasys": ["oas"];
    readonly "application/vnd.fujitsu.oasys2": ["oa2"];
    readonly "application/vnd.fujitsu.oasys3": ["oa3"];
    readonly "application/vnd.fujitsu.oasysgp": ["fg5"];
    readonly "application/vnd.fujitsu.oasysprs": ["bh2"];
    readonly "application/vnd.fujixerox.ddd": ["ddd"];
    readonly "application/vnd.fujixerox.docuworks": ["xdw"];
    readonly "application/vnd.fujixerox.docuworks.binder": ["xbd"];
    readonly "application/vnd.fuzzysheet": ["fzs"];
    readonly "application/vnd.genomatix.tuxedo": ["txd"];
    readonly "application/vnd.geogebra.file": ["ggb"];
    readonly "application/vnd.geogebra.slides": ["ggs"];
    readonly "application/vnd.geogebra.tool": ["ggt"];
    readonly "application/vnd.geometry-explorer": ["gex", "gre"];
    readonly "application/vnd.geonext": ["gxt"];
    readonly "application/vnd.geoplan": ["g2w"];
    readonly "application/vnd.geospace": ["g3w"];
    readonly "application/vnd.gmx": ["gmx"];
    readonly "application/vnd.google-apps.document": ["gdoc"];
    readonly "application/vnd.google-apps.drawing": ["gdraw"];
    readonly "application/vnd.google-apps.form": ["gform"];
    readonly "application/vnd.google-apps.jam": ["gjam"];
    readonly "application/vnd.google-apps.map": ["gmap"];
    readonly "application/vnd.google-apps.presentation": ["gslides"];
    readonly "application/vnd.google-apps.script": ["gscript"];
    readonly "application/vnd.google-apps.site": ["gsite"];
    readonly "application/vnd.google-apps.spreadsheet": ["gsheet"];
    readonly "application/vnd.google-earth.kml+xml": ["kml"];
    readonly "application/vnd.google-earth.kmz": ["kmz"];
    readonly "application/vnd.gov.sk.xmldatacontainer+xml": ["xdcf"];
    readonly "application/vnd.grafeq": ["gqf", "gqs"];
    readonly "application/vnd.groove-account": ["gac"];
    readonly "application/vnd.groove-help": ["ghf"];
    readonly "application/vnd.groove-identity-message": ["gim"];
    readonly "application/vnd.groove-injector": ["grv"];
    readonly "application/vnd.groove-tool-message": ["gtm"];
    readonly "application/vnd.groove-tool-template": ["tpl"];
    readonly "application/vnd.groove-vcard": ["vcg"];
    readonly "application/vnd.hal+xml": ["hal"];
    readonly "application/vnd.handheld-entertainment+xml": ["zmm"];
    readonly "application/vnd.hbci": ["hbci"];
    readonly "application/vnd.hhe.lesson-player": ["les"];
    readonly "application/vnd.hp-hpgl": ["hpgl"];
    readonly "application/vnd.hp-hpid": ["hpid"];
    readonly "application/vnd.hp-hps": ["hps"];
    readonly "application/vnd.hp-jlyt": ["jlt"];
    readonly "application/vnd.hp-pcl": ["pcl"];
    readonly "application/vnd.hp-pclxl": ["pclxl"];
    readonly "application/vnd.hydrostatix.sof-data": ["sfd-hdstx"];
    readonly "application/vnd.ibm.minipay": ["mpy"];
    readonly "application/vnd.ibm.modcap": ["afp", "listafp", "list3820"];
    readonly "application/vnd.ibm.rights-management": ["irm"];
    readonly "application/vnd.ibm.secure-container": ["sc"];
    readonly "application/vnd.iccprofile": ["icc", "icm"];
    readonly "application/vnd.igloader": ["igl"];
    readonly "application/vnd.immervision-ivp": ["ivp"];
    readonly "application/vnd.immervision-ivu": ["ivu"];
    readonly "application/vnd.insors.igm": ["igm"];
    readonly "application/vnd.intercon.formnet": ["xpw", "xpx"];
    readonly "application/vnd.intergeo": ["i2g"];
    readonly "application/vnd.intu.qbo": ["qbo"];
    readonly "application/vnd.intu.qfx": ["qfx"];
    readonly "application/vnd.ipunplugged.rcprofile": ["rcprofile"];
    readonly "application/vnd.irepository.package+xml": ["irp"];
    readonly "application/vnd.is-xpr": ["xpr"];
    readonly "application/vnd.isac.fcs": ["fcs"];
    readonly "application/vnd.jam": ["jam"];
    readonly "application/vnd.jcp.javame.midlet-rms": ["rms"];
    readonly "application/vnd.jisp": ["jisp"];
    readonly "application/vnd.joost.joda-archive": ["joda"];
    readonly "application/vnd.kahootz": ["ktz", "ktr"];
    readonly "application/vnd.kde.karbon": ["karbon"];
    readonly "application/vnd.kde.kchart": ["chrt"];
    readonly "application/vnd.kde.kformula": ["kfo"];
    readonly "application/vnd.kde.kivio": ["flw"];
    readonly "application/vnd.kde.kontour": ["kon"];
    readonly "application/vnd.kde.kpresenter": ["kpr", "kpt"];
    readonly "application/vnd.kde.kspread": ["ksp"];
    readonly "application/vnd.kde.kword": ["kwd", "kwt"];
    readonly "application/vnd.kenameaapp": ["htke"];
    readonly "application/vnd.kidspiration": ["kia"];
    readonly "application/vnd.kinar": ["kne", "knp"];
    readonly "application/vnd.koan": ["skp", "skd", "skt", "skm"];
    readonly "application/vnd.kodak-descriptor": ["sse"];
    readonly "application/vnd.las.las+xml": ["lasxml"];
    readonly "application/vnd.llamagraphics.life-balance.desktop": ["lbd"];
    readonly "application/vnd.llamagraphics.life-balance.exchange+xml": ["lbe"];
    readonly "application/vnd.lotus-1-2-3": ["123"];
    readonly "application/vnd.lotus-approach": ["apr"];
    readonly "application/vnd.lotus-freelance": ["pre"];
    readonly "application/vnd.lotus-notes": ["nsf"];
    readonly "application/vnd.lotus-organizer": ["org"];
    readonly "application/vnd.lotus-screencam": ["scm"];
    readonly "application/vnd.lotus-wordpro": ["lwp"];
    readonly "application/vnd.macports.portpkg": ["portpkg"];
    readonly "application/vnd.mapbox-vector-tile": ["mvt"];
    readonly "application/vnd.mcd": ["mcd"];
    readonly "application/vnd.medcalcdata": ["mc1"];
    readonly "application/vnd.mediastation.cdkey": ["cdkey"];
    readonly "application/vnd.mfer": ["mwf"];
    readonly "application/vnd.mfmp": ["mfm"];
    readonly "application/vnd.micrografx.flo": ["flo"];
    readonly "application/vnd.micrografx.igx": ["igx"];
    readonly "application/vnd.mif": ["mif"];
    readonly "application/vnd.mobius.daf": ["daf"];
    readonly "application/vnd.mobius.dis": ["dis"];
    readonly "application/vnd.mobius.mbk": ["mbk"];
    readonly "application/vnd.mobius.mqy": ["mqy"];
    readonly "application/vnd.mobius.msl": ["msl"];
    readonly "application/vnd.mobius.plc": ["plc"];
    readonly "application/vnd.mobius.txf": ["txf"];
    readonly "application/vnd.mophun.application": ["mpn"];
    readonly "application/vnd.mophun.certificate": ["mpc"];
    readonly "application/vnd.mozilla.xul+xml": ["xul"];
    readonly "application/vnd.ms-artgalry": ["cil"];
    readonly "application/vnd.ms-cab-compressed": ["cab"];
    readonly "application/vnd.ms-excel": ["xls", "xlm", "xla", "xlc", "xlt", "xlw"];
    readonly "application/vnd.ms-excel.addin.macroenabled.12": ["xlam"];
    readonly "application/vnd.ms-excel.sheet.binary.macroenabled.12": ["xlsb"];
    readonly "application/vnd.ms-excel.sheet.macroenabled.12": ["xlsm"];
    readonly "application/vnd.ms-excel.template.macroenabled.12": ["xltm"];
    readonly "application/vnd.ms-fontobject": ["eot"];
    readonly "application/vnd.ms-htmlhelp": ["chm"];
    readonly "application/vnd.ms-ims": ["ims"];
    readonly "application/vnd.ms-lrm": ["lrm"];
    readonly "application/vnd.ms-officetheme": ["thmx"];
    readonly "application/vnd.ms-outlook": ["msg"];
    readonly "application/vnd.ms-pki.seccat": ["cat"];
    readonly "application/vnd.ms-pki.stl": ["*stl"];
    readonly "application/vnd.ms-powerpoint": ["ppt", "pps", "pot"];
    readonly "application/vnd.ms-powerpoint.addin.macroenabled.12": ["ppam"];
    readonly "application/vnd.ms-powerpoint.presentation.macroenabled.12": ["pptm"];
    readonly "application/vnd.ms-powerpoint.slide.macroenabled.12": ["sldm"];
    readonly "application/vnd.ms-powerpoint.slideshow.macroenabled.12": ["ppsm"];
    readonly "application/vnd.ms-powerpoint.template.macroenabled.12": ["potm"];
    readonly "application/vnd.ms-project": ["*mpp", "mpt"];
    readonly "application/vnd.ms-visio.viewer": ["vdx"];
    readonly "application/vnd.ms-word.document.macroenabled.12": ["docm"];
    readonly "application/vnd.ms-word.template.macroenabled.12": ["dotm"];
    readonly "application/vnd.ms-works": ["wps", "wks", "wcm", "wdb"];
    readonly "application/vnd.ms-wpl": ["wpl"];
    readonly "application/vnd.ms-xpsdocument": ["xps"];
    readonly "application/vnd.mseq": ["mseq"];
    readonly "application/vnd.musician": ["mus"];
    readonly "application/vnd.muvee.style": ["msty"];
    readonly "application/vnd.mynfc": ["taglet"];
    readonly "application/vnd.nato.bindingdataobject+xml": ["bdo"];
    readonly "application/vnd.neurolanguage.nlu": ["nlu"];
    readonly "application/vnd.nitf": ["ntf", "nitf"];
    readonly "application/vnd.noblenet-directory": ["nnd"];
    readonly "application/vnd.noblenet-sealer": ["nns"];
    readonly "application/vnd.noblenet-web": ["nnw"];
    readonly "application/vnd.nokia.n-gage.ac+xml": ["*ac"];
    readonly "application/vnd.nokia.n-gage.data": ["ngdat"];
    readonly "application/vnd.nokia.n-gage.symbian.install": ["n-gage"];
    readonly "application/vnd.nokia.radio-preset": ["rpst"];
    readonly "application/vnd.nokia.radio-presets": ["rpss"];
    readonly "application/vnd.novadigm.edm": ["edm"];
    readonly "application/vnd.novadigm.edx": ["edx"];
    readonly "application/vnd.novadigm.ext": ["ext"];
    readonly "application/vnd.oasis.opendocument.chart": ["odc"];
    readonly "application/vnd.oasis.opendocument.chart-template": ["otc"];
    readonly "application/vnd.oasis.opendocument.database": ["odb"];
    readonly "application/vnd.oasis.opendocument.formula": ["odf"];
    readonly "application/vnd.oasis.opendocument.formula-template": ["odft"];
    readonly "application/vnd.oasis.opendocument.graphics": ["odg"];
    readonly "application/vnd.oasis.opendocument.graphics-template": ["otg"];
    readonly "application/vnd.oasis.opendocument.image": ["odi"];
    readonly "application/vnd.oasis.opendocument.image-template": ["oti"];
    readonly "application/vnd.oasis.opendocument.presentation": ["odp"];
    readonly "application/vnd.oasis.opendocument.presentation-template": ["otp"];
    readonly "application/vnd.oasis.opendocument.spreadsheet": ["ods"];
    readonly "application/vnd.oasis.opendocument.spreadsheet-template": ["ots"];
    readonly "application/vnd.oasis.opendocument.text": ["odt"];
    readonly "application/vnd.oasis.opendocument.text-master": ["odm"];
    readonly "application/vnd.oasis.opendocument.text-template": ["ott"];
    readonly "application/vnd.oasis.opendocument.text-web": ["oth"];
    readonly "application/vnd.olpc-sugar": ["xo"];
    readonly "application/vnd.oma.dd2+xml": ["dd2"];
    readonly "application/vnd.openblox.game+xml": ["obgx"];
    readonly "application/vnd.openofficeorg.extension": ["oxt"];
    readonly "application/vnd.openstreetmap.data+xml": ["osm"];
    readonly "application/vnd.openxmlformats-officedocument.presentationml.presentation": ["pptx"];
    readonly "application/vnd.openxmlformats-officedocument.presentationml.slide": ["sldx"];
    readonly "application/vnd.openxmlformats-officedocument.presentationml.slideshow": ["ppsx"];
    readonly "application/vnd.openxmlformats-officedocument.presentationml.template": ["potx"];
    readonly "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet": ["xlsx"];
    readonly "application/vnd.openxmlformats-officedocument.spreadsheetml.template": ["xltx"];
    readonly "application/vnd.openxmlformats-officedocument.wordprocessingml.document": ["docx"];
    readonly "application/vnd.openxmlformats-officedocument.wordprocessingml.template": ["dotx"];
    readonly "application/vnd.osgeo.mapguide.package": ["mgp"];
    readonly "application/vnd.osgi.dp": ["dp"];
    readonly "application/vnd.osgi.subsystem": ["esa"];
    readonly "application/vnd.palm": ["pdb", "pqa", "oprc"];
    readonly "application/vnd.pawaafile": ["paw"];
    readonly "application/vnd.pg.format": ["str"];
    readonly "application/vnd.pg.osasli": ["ei6"];
    readonly "application/vnd.picsel": ["efif"];
    readonly "application/vnd.pmi.widget": ["wg"];
    readonly "application/vnd.pocketlearn": ["plf"];
    readonly "application/vnd.powerbuilder6": ["pbd"];
    readonly "application/vnd.previewsystems.box": ["box"];
    readonly "application/vnd.procrate.brushset": ["brushset"];
    readonly "application/vnd.procreate.brush": ["brush"];
    readonly "application/vnd.procreate.dream": ["drm"];
    readonly "application/vnd.proteus.magazine": ["mgz"];
    readonly "application/vnd.publishare-delta-tree": ["qps"];
    readonly "application/vnd.pvi.ptid1": ["ptid"];
    readonly "application/vnd.pwg-xhtml-print+xml": ["xhtm"];
    readonly "application/vnd.quark.quarkxpress": ["qxd", "qxt", "qwd", "qwt", "qxl", "qxb"];
    readonly "application/vnd.rar": ["rar"];
    readonly "application/vnd.realvnc.bed": ["bed"];
    readonly "application/vnd.recordare.musicxml": ["mxl"];
    readonly "application/vnd.recordare.musicxml+xml": ["musicxml"];
    readonly "application/vnd.rig.cryptonote": ["cryptonote"];
    readonly "application/vnd.rim.cod": ["cod"];
    readonly "application/vnd.rn-realmedia": ["rm"];
    readonly "application/vnd.rn-realmedia-vbr": ["rmvb"];
    readonly "application/vnd.route66.link66+xml": ["link66"];
    readonly "application/vnd.sailingtracker.track": ["st"];
    readonly "application/vnd.seemail": ["see"];
    readonly "application/vnd.sema": ["sema"];
    readonly "application/vnd.semd": ["semd"];
    readonly "application/vnd.semf": ["semf"];
    readonly "application/vnd.shana.informed.formdata": ["ifm"];
    readonly "application/vnd.shana.informed.formtemplate": ["itp"];
    readonly "application/vnd.shana.informed.interchange": ["iif"];
    readonly "application/vnd.shana.informed.package": ["ipk"];
    readonly "application/vnd.simtech-mindmapper": ["twd", "twds"];
    readonly "application/vnd.smaf": ["mmf"];
    readonly "application/vnd.smart.teacher": ["teacher"];
    readonly "application/vnd.software602.filler.form+xml": ["fo"];
    readonly "application/vnd.solent.sdkm+xml": ["sdkm", "sdkd"];
    readonly "application/vnd.spotfire.dxp": ["dxp"];
    readonly "application/vnd.spotfire.sfs": ["sfs"];
    readonly "application/vnd.stardivision.calc": ["sdc"];
    readonly "application/vnd.stardivision.draw": ["sda"];
    readonly "application/vnd.stardivision.impress": ["sdd"];
    readonly "application/vnd.stardivision.math": ["smf"];
    readonly "application/vnd.stardivision.writer": ["sdw", "vor"];
    readonly "application/vnd.stardivision.writer-global": ["sgl"];
    readonly "application/vnd.stepmania.package": ["smzip"];
    readonly "application/vnd.stepmania.stepchart": ["sm"];
    readonly "application/vnd.sun.wadl+xml": ["wadl"];
    readonly "application/vnd.sun.xml.calc": ["sxc"];
    readonly "application/vnd.sun.xml.calc.template": ["stc"];
    readonly "application/vnd.sun.xml.draw": ["sxd"];
    readonly "application/vnd.sun.xml.draw.template": ["std"];
    readonly "application/vnd.sun.xml.impress": ["sxi"];
    readonly "application/vnd.sun.xml.impress.template": ["sti"];
    readonly "application/vnd.sun.xml.math": ["sxm"];
    readonly "application/vnd.sun.xml.writer": ["sxw"];
    readonly "application/vnd.sun.xml.writer.global": ["sxg"];
    readonly "application/vnd.sun.xml.writer.template": ["stw"];
    readonly "application/vnd.sus-calendar": ["sus", "susp"];
    readonly "application/vnd.svd": ["svd"];
    readonly "application/vnd.symbian.install": ["sis", "sisx"];
    readonly "application/vnd.syncml+xml": ["xsm"];
    readonly "application/vnd.syncml.dm+wbxml": ["bdm"];
    readonly "application/vnd.syncml.dm+xml": ["xdm"];
    readonly "application/vnd.syncml.dmddf+xml": ["ddf"];
    readonly "application/vnd.tao.intent-module-archive": ["tao"];
    readonly "application/vnd.tcpdump.pcap": ["pcap", "cap", "dmp"];
    readonly "application/vnd.tmobile-livetv": ["tmo"];
    readonly "application/vnd.trid.tpt": ["tpt"];
    readonly "application/vnd.triscape.mxs": ["mxs"];
    readonly "application/vnd.trueapp": ["tra"];
    readonly "application/vnd.ufdl": ["ufd", "ufdl"];
    readonly "application/vnd.uiq.theme": ["utz"];
    readonly "application/vnd.umajin": ["umj"];
    readonly "application/vnd.unity": ["unityweb"];
    readonly "application/vnd.uoml+xml": ["uoml", "uo"];
    readonly "application/vnd.vcx": ["vcx"];
    readonly "application/vnd.visio": ["vsd", "vst", "vss", "vsw", "vsdx", "vtx"];
    readonly "application/vnd.visionary": ["vis"];
    readonly "application/vnd.vsf": ["vsf"];
    readonly "application/vnd.wap.wbxml": ["wbxml"];
    readonly "application/vnd.wap.wmlc": ["wmlc"];
    readonly "application/vnd.wap.wmlscriptc": ["wmlsc"];
    readonly "application/vnd.webturbo": ["wtb"];
    readonly "application/vnd.wolfram.player": ["nbp"];
    readonly "application/vnd.wordperfect": ["wpd"];
    readonly "application/vnd.wqd": ["wqd"];
    readonly "application/vnd.wt.stf": ["stf"];
    readonly "application/vnd.xara": ["xar"];
    readonly "application/vnd.xfdl": ["xfdl"];
    readonly "application/vnd.yamaha.hv-dic": ["hvd"];
    readonly "application/vnd.yamaha.hv-script": ["hvs"];
    readonly "application/vnd.yamaha.hv-voice": ["hvp"];
    readonly "application/vnd.yamaha.openscoreformat": ["osf"];
    readonly "application/vnd.yamaha.openscoreformat.osfpvg+xml": ["osfpvg"];
    readonly "application/vnd.yamaha.smaf-audio": ["saf"];
    readonly "application/vnd.yamaha.smaf-phrase": ["spf"];
    readonly "application/vnd.yellowriver-custom-menu": ["cmp"];
    readonly "application/vnd.zul": ["zir", "zirz"];
    readonly "application/vnd.zzazz.deck+xml": ["zaz"];
    readonly "application/x-7z-compressed": ["7z"];
    readonly "application/x-abiword": ["abw"];
    readonly "application/x-ace-compressed": ["ace"];
    readonly "application/x-apple-diskimage": ["*dmg"];
    readonly "application/x-arj": ["arj"];
    readonly "application/x-authorware-bin": ["aab", "x32", "u32", "vox"];
    readonly "application/x-authorware-map": ["aam"];
    readonly "application/x-authorware-seg": ["aas"];
    readonly "application/x-bcpio": ["bcpio"];
    readonly "application/x-bdoc": ["*bdoc"];
    readonly "application/x-bittorrent": ["torrent"];
    readonly "application/x-blender": ["blend"];
    readonly "application/x-blorb": ["blb", "blorb"];
    readonly "application/x-bzip": ["bz"];
    readonly "application/x-bzip2": ["bz2", "boz"];
    readonly "application/x-cbr": ["cbr", "cba", "cbt", "cbz", "cb7"];
    readonly "application/x-cdlink": ["vcd"];
    readonly "application/x-cfs-compressed": ["cfs"];
    readonly "application/x-chat": ["chat"];
    readonly "application/x-chess-pgn": ["pgn"];
    readonly "application/x-chrome-extension": ["crx"];
    readonly "application/x-cocoa": ["cco"];
    readonly "application/x-compressed": ["*rar"];
    readonly "application/x-conference": ["nsc"];
    readonly "application/x-cpio": ["cpio"];
    readonly "application/x-csh": ["csh"];
    readonly "application/x-debian-package": ["*deb", "udeb"];
    readonly "application/x-dgc-compressed": ["dgc"];
    readonly "application/x-director": ["dir", "dcr", "dxr", "cst", "cct", "cxt", "w3d", "fgd", "swa"];
    readonly "application/x-doom": ["wad"];
    readonly "application/x-dtbncx+xml": ["ncx"];
    readonly "application/x-dtbook+xml": ["dtb"];
    readonly "application/x-dtbresource+xml": ["res"];
    readonly "application/x-dvi": ["dvi"];
    readonly "application/x-envoy": ["evy"];
    readonly "application/x-eva": ["eva"];
    readonly "application/x-font-bdf": ["bdf"];
    readonly "application/x-font-ghostscript": ["gsf"];
    readonly "application/x-font-linux-psf": ["psf"];
    readonly "application/x-font-pcf": ["pcf"];
    readonly "application/x-font-snf": ["snf"];
    readonly "application/x-font-type1": ["pfa", "pfb", "pfm", "afm"];
    readonly "application/x-freearc": ["arc"];
    readonly "application/x-futuresplash": ["spl"];
    readonly "application/x-gca-compressed": ["gca"];
    readonly "application/x-glulx": ["ulx"];
    readonly "application/x-gnumeric": ["gnumeric"];
    readonly "application/x-gramps-xml": ["gramps"];
    readonly "application/x-gtar": ["gtar"];
    readonly "application/x-hdf": ["hdf"];
    readonly "application/x-httpd-php": ["php"];
    readonly "application/x-install-instructions": ["install"];
    readonly "application/x-ipynb+json": ["ipynb"];
    readonly "application/x-iso9660-image": ["*iso"];
    readonly "application/x-iwork-keynote-sffkey": ["*key"];
    readonly "application/x-iwork-numbers-sffnumbers": ["*numbers"];
    readonly "application/x-iwork-pages-sffpages": ["*pages"];
    readonly "application/x-java-archive-diff": ["jardiff"];
    readonly "application/x-java-jnlp-file": ["jnlp"];
    readonly "application/x-keepass2": ["kdbx"];
    readonly "application/x-latex": ["latex"];
    readonly "application/x-lua-bytecode": ["luac"];
    readonly "application/x-lzh-compressed": ["lzh", "lha"];
    readonly "application/x-makeself": ["run"];
    readonly "application/x-mie": ["mie"];
    readonly "application/x-mobipocket-ebook": ["*prc", "mobi"];
    readonly "application/x-ms-application": ["application"];
    readonly "application/x-ms-shortcut": ["lnk"];
    readonly "application/x-ms-wmd": ["wmd"];
    readonly "application/x-ms-wmz": ["wmz"];
    readonly "application/x-ms-xbap": ["xbap"];
    readonly "application/x-msaccess": ["mdb"];
    readonly "application/x-msbinder": ["obd"];
    readonly "application/x-mscardfile": ["crd"];
    readonly "application/x-msclip": ["clp"];
    readonly "application/x-msdos-program": ["*exe"];
    readonly "application/x-msdownload": ["*exe", "*dll", "com", "bat", "*msi"];
    readonly "application/x-msmediaview": ["mvb", "m13", "m14"];
    readonly "application/x-msmetafile": ["*wmf", "*wmz", "*emf", "emz"];
    readonly "application/x-msmoney": ["mny"];
    readonly "application/x-mspublisher": ["pub"];
    readonly "application/x-msschedule": ["scd"];
    readonly "application/x-msterminal": ["trm"];
    readonly "application/x-mswrite": ["wri"];
    readonly "application/x-netcdf": ["nc", "cdf"];
    readonly "application/x-ns-proxy-autoconfig": ["pac"];
    readonly "application/x-nzb": ["nzb"];
    readonly "application/x-perl": ["pl", "pm"];
    readonly "application/x-pilot": ["*prc", "*pdb"];
    readonly "application/x-pkcs12": ["p12", "pfx"];
    readonly "application/x-pkcs7-certificates": ["p7b", "spc"];
    readonly "application/x-pkcs7-certreqresp": ["p7r"];
    readonly "application/x-rar-compressed": ["*rar"];
    readonly "application/x-redhat-package-manager": ["rpm"];
    readonly "application/x-research-info-systems": ["ris"];
    readonly "application/x-sea": ["sea"];
    readonly "application/x-sh": ["sh"];
    readonly "application/x-shar": ["shar"];
    readonly "application/x-shockwave-flash": ["swf"];
    readonly "application/x-silverlight-app": ["xap"];
    readonly "application/x-sql": ["*sql"];
    readonly "application/x-stuffit": ["sit"];
    readonly "application/x-stuffitx": ["sitx"];
    readonly "application/x-subrip": ["srt"];
    readonly "application/x-sv4cpio": ["sv4cpio"];
    readonly "application/x-sv4crc": ["sv4crc"];
    readonly "application/x-t3vm-image": ["t3"];
    readonly "application/x-tads": ["gam"];
    readonly "application/x-tar": ["tar"];
    readonly "application/x-tcl": ["tcl", "tk"];
    readonly "application/x-tex": ["tex"];
    readonly "application/x-tex-tfm": ["tfm"];
    readonly "application/x-texinfo": ["texinfo", "texi"];
    readonly "application/x-tgif": ["*obj"];
    readonly "application/x-ustar": ["ustar"];
    readonly "application/x-virtualbox-hdd": ["hdd"];
    readonly "application/x-virtualbox-ova": ["ova"];
    readonly "application/x-virtualbox-ovf": ["ovf"];
    readonly "application/x-virtualbox-vbox": ["vbox"];
    readonly "application/x-virtualbox-vbox-extpack": ["vbox-extpack"];
    readonly "application/x-virtualbox-vdi": ["vdi"];
    readonly "application/x-virtualbox-vhd": ["vhd"];
    readonly "application/x-virtualbox-vmdk": ["vmdk"];
    readonly "application/x-wais-source": ["src"];
    readonly "application/x-web-app-manifest+json": ["webapp"];
    readonly "application/x-x509-ca-cert": ["der", "crt", "pem"];
    readonly "application/x-xfig": ["fig"];
    readonly "application/x-xliff+xml": ["*xlf"];
    readonly "application/x-xpinstall": ["xpi"];
    readonly "application/x-xz": ["xz"];
    readonly "application/x-zip-compressed": ["*zip"];
    readonly "application/x-zmachine": ["z1", "z2", "z3", "z4", "z5", "z6", "z7", "z8"];
    readonly "audio/vnd.dece.audio": ["uva", "uvva"];
    readonly "audio/vnd.digital-winds": ["eol"];
    readonly "audio/vnd.dra": ["dra"];
    readonly "audio/vnd.dts": ["dts"];
    readonly "audio/vnd.dts.hd": ["dtshd"];
    readonly "audio/vnd.lucent.voice": ["lvp"];
    readonly "audio/vnd.ms-playready.media.pya": ["pya"];
    readonly "audio/vnd.nuera.ecelp4800": ["ecelp4800"];
    readonly "audio/vnd.nuera.ecelp7470": ["ecelp7470"];
    readonly "audio/vnd.nuera.ecelp9600": ["ecelp9600"];
    readonly "audio/vnd.rip": ["rip"];
    readonly "audio/x-aac": ["*aac"];
    readonly "audio/x-aiff": ["aif", "aiff", "aifc"];
    readonly "audio/x-caf": ["caf"];
    readonly "audio/x-flac": ["flac"];
    readonly "audio/x-m4a": ["*m4a"];
    readonly "audio/x-matroska": ["mka"];
    readonly "audio/x-mpegurl": ["m3u"];
    readonly "audio/x-ms-wax": ["wax"];
    readonly "audio/x-ms-wma": ["wma"];
    readonly "audio/x-pn-realaudio": ["ram", "ra"];
    readonly "audio/x-pn-realaudio-plugin": ["rmp"];
    readonly "audio/x-realaudio": ["*ra"];
    readonly "audio/x-wav": ["*wav"];
    readonly "chemical/x-cdx": ["cdx"];
    readonly "chemical/x-cif": ["cif"];
    readonly "chemical/x-cmdf": ["cmdf"];
    readonly "chemical/x-cml": ["cml"];
    readonly "chemical/x-csml": ["csml"];
    readonly "chemical/x-xyz": ["xyz"];
    readonly "image/prs.btif": ["btif", "btf"];
    readonly "image/prs.pti": ["pti"];
    readonly "image/vnd.adobe.photoshop": ["psd"];
    readonly "image/vnd.airzip.accelerator.azv": ["azv"];
    readonly "image/vnd.blockfact.facti": ["facti"];
    readonly "image/vnd.dece.graphic": ["uvi", "uvvi", "uvg", "uvvg"];
    readonly "image/vnd.djvu": ["djvu", "djv"];
    readonly "image/vnd.dvb.subtitle": ["*sub"];
    readonly "image/vnd.dwg": ["dwg"];
    readonly "image/vnd.dxf": ["dxf"];
    readonly "image/vnd.fastbidsheet": ["fbs"];
    readonly "image/vnd.fpx": ["fpx"];
    readonly "image/vnd.fst": ["fst"];
    readonly "image/vnd.fujixerox.edmics-mmr": ["mmr"];
    readonly "image/vnd.fujixerox.edmics-rlc": ["rlc"];
    readonly "image/vnd.microsoft.icon": ["ico"];
    readonly "image/vnd.ms-dds": ["dds"];
    readonly "image/vnd.ms-modi": ["mdi"];
    readonly "image/vnd.ms-photo": ["wdp"];
    readonly "image/vnd.net-fpx": ["npx"];
    readonly "image/vnd.pco.b16": ["b16"];
    readonly "image/vnd.tencent.tap": ["tap"];
    readonly "image/vnd.valve.source.texture": ["vtf"];
    readonly "image/vnd.wap.wbmp": ["wbmp"];
    readonly "image/vnd.xiff": ["xif"];
    readonly "image/vnd.zbrush.pcx": ["pcx"];
    readonly "image/x-3ds": ["3ds"];
    readonly "image/x-adobe-dng": ["dng"];
    readonly "image/x-cmu-raster": ["ras"];
    readonly "image/x-cmx": ["cmx"];
    readonly "image/x-freehand": ["fh", "fhc", "fh4", "fh5", "fh7"];
    readonly "image/x-icon": ["*ico"];
    readonly "image/x-jng": ["jng"];
    readonly "image/x-mrsid-image": ["sid"];
    readonly "image/x-ms-bmp": ["*bmp"];
    readonly "image/x-pcx": ["*pcx"];
    readonly "image/x-pict": ["pic", "pct"];
    readonly "image/x-portable-anymap": ["pnm"];
    readonly "image/x-portable-bitmap": ["pbm"];
    readonly "image/x-portable-graymap": ["pgm"];
    readonly "image/x-portable-pixmap": ["ppm"];
    readonly "image/x-rgb": ["rgb"];
    readonly "image/x-tga": ["tga"];
    readonly "image/x-xbitmap": ["xbm"];
    readonly "image/x-xpixmap": ["xpm"];
    readonly "image/x-xwindowdump": ["xwd"];
    readonly "message/vnd.wfa.wsc": ["wsc"];
    readonly "model/vnd.bary": ["bary"];
    readonly "model/vnd.cld": ["cld"];
    readonly "model/vnd.collada+xml": ["dae"];
    readonly "model/vnd.dwf": ["dwf"];
    readonly "model/vnd.gdl": ["gdl"];
    readonly "model/vnd.gtw": ["gtw"];
    readonly "model/vnd.mts": ["*mts"];
    readonly "model/vnd.opengex": ["ogex"];
    readonly "model/vnd.parasolid.transmit.binary": ["x_b"];
    readonly "model/vnd.parasolid.transmit.text": ["x_t"];
    readonly "model/vnd.pytha.pyox": ["pyo", "pyox"];
    readonly "model/vnd.sap.vds": ["vds"];
    readonly "model/vnd.usda": ["usda"];
    readonly "model/vnd.usdz+zip": ["usdz"];
    readonly "model/vnd.valve.source.compiled-map": ["bsp"];
    readonly "model/vnd.vtu": ["vtu"];
    readonly "text/prs.lines.tag": ["dsc"];
    readonly "text/vnd.curl": ["curl"];
    readonly "text/vnd.curl.dcurl": ["dcurl"];
    readonly "text/vnd.curl.mcurl": ["mcurl"];
    readonly "text/vnd.curl.scurl": ["scurl"];
    readonly "text/vnd.dvb.subtitle": ["sub"];
    readonly "text/vnd.familysearch.gedcom": ["ged"];
    readonly "text/vnd.fly": ["fly"];
    readonly "text/vnd.fmi.flexstor": ["flx"];
    readonly "text/vnd.graphviz": ["gv"];
    readonly "text/vnd.in3d.3dml": ["3dml"];
    readonly "text/vnd.in3d.spot": ["spot"];
    readonly "text/vnd.sun.j2me.app-descriptor": ["jad"];
    readonly "text/vnd.wap.wml": ["wml"];
    readonly "text/vnd.wap.wmlscript": ["wmls"];
    readonly "text/x-asm": ["s", "asm"];
    readonly "text/x-c": ["c", "cc", "cxx", "cpp", "h", "hh", "dic"];
    readonly "text/x-component": ["htc"];
    readonly "text/x-fortran": ["f", "for", "f77", "f90"];
    readonly "text/x-handlebars-template": ["hbs"];
    readonly "text/x-java-source": ["java"];
    readonly "text/x-lua": ["lua"];
    readonly "text/x-markdown": ["mkd"];
    readonly "text/x-nfo": ["nfo"];
    readonly "text/x-opml": ["opml"];
    readonly "text/x-org": ["*org"];
    readonly "text/x-pascal": ["p", "pas"];
    readonly "text/x-processing": ["pde"];
    readonly "text/x-sass": ["sass"];
    readonly "text/x-scss": ["scss"];
    readonly "text/x-setext": ["etx"];
    readonly "text/x-sfv": ["sfv"];
    readonly "text/x-suse-ymp": ["ymp"];
    readonly "text/x-uuencode": ["uu"];
    readonly "text/x-vcalendar": ["vcs"];
    readonly "text/x-vcard": ["vcf"];
    readonly "video/vnd.dece.hd": ["uvh", "uvvh"];
    readonly "video/vnd.dece.mobile": ["uvm", "uvvm"];
    readonly "video/vnd.dece.pd": ["uvp", "uvvp"];
    readonly "video/vnd.dece.sd": ["uvs", "uvvs"];
    readonly "video/vnd.dece.video": ["uvv", "uvvv"];
    readonly "video/vnd.dvb.file": ["dvb"];
    readonly "video/vnd.fvt": ["fvt"];
    readonly "video/vnd.mpegurl": ["mxu", "m4u"];
    readonly "video/vnd.ms-playready.media.pyv": ["pyv"];
    readonly "video/vnd.uvvu.mp4": ["uvu", "uvvu"];
    readonly "video/vnd.vivo": ["viv"];
    readonly "video/x-f4v": ["f4v"];
    readonly "video/x-fli": ["fli"];
    readonly "video/x-flv": ["flv"];
    readonly "video/x-m4v": ["m4v"];
    readonly "video/x-matroska": ["mkv", "mk3d", "mks"];
    readonly "video/x-mng": ["mng"];
    readonly "video/x-ms-asf": ["asf", "asx"];
    readonly "video/x-ms-vob": ["vob"];
    readonly "video/x-ms-wm": ["wm"];
    readonly "video/x-ms-wmv": ["wmv"];
    readonly "video/x-ms-wmx": ["wmx"];
    readonly "video/x-ms-wvx": ["wvx"];
    readonly "video/x-msvideo": ["avi"];
    readonly "video/x-sgi-movie": ["movie"];
    readonly "video/x-smv": ["smv"];
    readonly "x-conference/x-cooltalk": ["ice"];
};
export type SupportedMimeType = keyof typeof types;
export type SupportedExtensionFile = (typeof types)[SupportedMimeType][number];
declare const mimeType: Map<string, "application/andrew-inset" | "application/appinstaller" | "application/applixware" | "application/appx" | "application/appxbundle" | "application/atom+xml" | "application/atomcat+xml" | "application/atomdeleted+xml" | "application/atomsvc+xml" | "application/atsc-dwd+xml" | "application/atsc-held+xml" | "application/atsc-rsat+xml" | "application/automationml-aml+xml" | "application/automationml-amlx+zip" | "application/bdoc" | "application/calendar+xml" | "application/ccxml+xml" | "application/cdfx+xml" | "application/cdmi-capability" | "application/cdmi-container" | "application/cdmi-domain" | "application/cdmi-object" | "application/cdmi-queue" | "application/cpl+xml" | "application/cu-seeme" | "application/cwl" | "application/dash+xml" | "application/dash-patch+xml" | "application/davmount+xml" | "application/dicom" | "application/docbook+xml" | "application/dssc+der" | "application/dssc+xml" | "application/ecmascript" | "application/emma+xml" | "application/emotionml+xml" | "application/epub+zip" | "application/exi" | "application/express" | "application/fdf" | "application/fdt+xml" | "application/font-tdpfr" | "application/geo+json" | "application/gml+xml" | "application/gpx+xml" | "application/gxf" | "application/gzip" | "application/hjson" | "application/hyperstudio" | "application/inkml+xml" | "application/ipfix" | "application/its+xml" | "application/java-archive" | "application/java-serialized-object" | "application/java-vm" | "application/javascript" | "application/json" | "application/json5" | "application/jsonml+json" | "application/ld+json" | "application/lgr+xml" | "application/lost+xml" | "application/mac-binhex40" | "application/mac-compactpro" | "application/mads+xml" | "application/manifest+json" | "application/marc" | "application/marcxml+xml" | "application/mathematica" | "application/mathml+xml" | "application/mbox" | "application/media-policy-dataset+xml" | "application/mediaservercontrol+xml" | "application/metalink+xml" | "application/metalink4+xml" | "application/mets+xml" | "application/mmt-aei+xml" | "application/mmt-usd+xml" | "application/mods+xml" | "application/mp21" | "application/mp4" | "application/msix" | "application/msixbundle" | "application/msword" | "application/mxf" | "application/n-quads" | "application/n-triples" | "application/node" | "application/octet-stream" | "application/oda" | "application/oebps-package+xml" | "application/ogg" | "application/omdoc+xml" | "application/onenote" | "application/oxps" | "application/p2p-overlay+xml" | "application/patch-ops-error+xml" | "application/pdf" | "application/pgp-encrypted" | "application/pgp-keys" | "application/pgp-signature" | "application/pics-rules" | "application/pkcs10" | "application/pkcs7-mime" | "application/pkcs7-signature" | "application/pkcs8" | "application/pkix-attr-cert" | "application/pkix-cert" | "application/pkix-crl" | "application/pkix-pkipath" | "application/pkixcmp" | "application/pls+xml" | "application/postscript" | "application/provenance+xml" | "application/pskc+xml" | "application/raml+yaml" | "application/rdf+xml" | "application/reginfo+xml" | "application/relax-ng-compact-syntax" | "application/resource-lists+xml" | "application/resource-lists-diff+xml" | "application/rls-services+xml" | "application/route-apd+xml" | "application/route-s-tsid+xml" | "application/route-usd+xml" | "application/rpki-ghostbusters" | "application/rpki-manifest" | "application/rpki-roa" | "application/rsd+xml" | "application/rss+xml" | "application/rtf" | "application/sbml+xml" | "application/scvp-cv-request" | "application/scvp-cv-response" | "application/scvp-vp-request" | "application/scvp-vp-response" | "application/sdp" | "application/senml+xml" | "application/sensml+xml" | "application/set-payment-initiation" | "application/set-registration-initiation" | "application/shf+xml" | "application/sieve" | "application/smil+xml" | "application/sparql-query" | "application/sparql-results+xml" | "application/sql" | "application/srgs" | "application/srgs+xml" | "application/sru+xml" | "application/ssdl+xml" | "application/ssml+xml" | "application/swid+xml" | "application/tei+xml" | "application/thraud+xml" | "application/timestamped-data" | "application/toml" | "application/trig" | "application/ttml+xml" | "application/ubjson" | "application/urc-ressheet+xml" | "application/urc-targetdesc+xml" | "application/voicexml+xml" | "application/wasm" | "application/watcherinfo+xml" | "application/widget" | "application/winhlp" | "application/wsdl+xml" | "application/wspolicy+xml" | "application/xaml+xml" | "application/xcap-att+xml" | "application/xcap-caps+xml" | "application/xcap-diff+xml" | "application/xcap-el+xml" | "application/xcap-ns+xml" | "application/xenc+xml" | "application/xfdf" | "application/xhtml+xml" | "application/xliff+xml" | "application/xml" | "application/xml-dtd" | "application/xop+xml" | "application/xproc+xml" | "application/xslt+xml" | "application/xspf+xml" | "application/xv+xml" | "application/yang" | "application/yin+xml" | "application/zip" | "application/zip+dotlottie" | "audio/3gpp" | "audio/aac" | "audio/adpcm" | "audio/amr" | "audio/basic" | "audio/midi" | "audio/mobile-xmf" | "audio/mp3" | "audio/mp4" | "audio/mpeg" | "audio/ogg" | "audio/s3m" | "audio/silk" | "audio/wav" | "audio/wave" | "audio/webm" | "audio/xm" | "font/collection" | "font/otf" | "font/ttf" | "font/woff" | "font/woff2" | "image/aces" | "image/apng" | "image/avci" | "image/avcs" | "image/avif" | "image/bmp" | "image/cgm" | "image/dicom-rle" | "image/dpx" | "image/emf" | "image/fits" | "image/g3fax" | "image/gif" | "image/heic" | "image/heic-sequence" | "image/heif" | "image/heif-sequence" | "image/hej2k" | "image/ief" | "image/jaii" | "image/jais" | "image/jls" | "image/jp2" | "image/jpeg" | "image/jph" | "image/jphc" | "image/jpm" | "image/jpx" | "image/jxl" | "image/jxr" | "image/jxra" | "image/jxrs" | "image/jxs" | "image/jxsc" | "image/jxsi" | "image/jxss" | "image/ktx" | "image/ktx2" | "image/pjpeg" | "image/png" | "image/sgi" | "image/svg+xml" | "image/t38" | "image/tiff" | "image/tiff-fx" | "image/webp" | "image/wmf" | "message/disposition-notification" | "message/global" | "message/global-delivery-status" | "message/global-disposition-notification" | "message/global-headers" | "message/rfc822" | "model/3mf" | "model/gltf+json" | "model/gltf-binary" | "model/iges" | "model/jt" | "model/mesh" | "model/mtl" | "model/obj" | "model/prc" | "model/step" | "model/step+xml" | "model/step+zip" | "model/step-xml+zip" | "model/stl" | "model/u3d" | "model/vrml" | "model/x3d+binary" | "model/x3d+fastinfoset" | "model/x3d+vrml" | "model/x3d+xml" | "model/x3d-vrml" | "text/cache-manifest" | "text/calendar" | "text/coffeescript" | "text/css" | "text/csv" | "text/html" | "text/jade" | "text/javascript" | "text/jsx" | "text/less" | "text/markdown" | "text/mathml" | "text/mdx" | "text/n3" | "text/plain" | "text/richtext" | "text/rtf" | "text/sgml" | "text/shex" | "text/slim" | "text/spdx" | "text/stylus" | "text/tab-separated-values" | "text/troff" | "text/turtle" | "text/uri-list" | "text/vcard" | "text/vtt" | "text/wgsl" | "text/xml" | "text/yaml" | "video/3gpp" | "video/3gpp2" | "video/h261" | "video/h263" | "video/h264" | "video/iso.segment" | "video/jpeg" | "video/jpm" | "video/mj2" | "video/mp2t" | "video/mp4" | "video/mpeg" | "video/ogg" | "video/quicktime" | "video/webm" | "application/prs.cww" | "application/prs.xsf+xml" | "application/vnd.1000minds.decision-model+xml" | "application/vnd.3gpp.pic-bw-large" | "application/vnd.3gpp.pic-bw-small" | "application/vnd.3gpp.pic-bw-var" | "application/vnd.3gpp2.tcap" | "application/vnd.3m.post-it-notes" | "application/vnd.accpac.simply.aso" | "application/vnd.accpac.simply.imp" | "application/vnd.acucobol" | "application/vnd.acucorp" | "application/vnd.adobe.air-application-installer-package+zip" | "application/vnd.adobe.formscentral.fcdt" | "application/vnd.adobe.fxp" | "application/vnd.adobe.xdp+xml" | "application/vnd.adobe.xfdf" | "application/vnd.age" | "application/vnd.ahead.space" | "application/vnd.airzip.filesecure.azf" | "application/vnd.airzip.filesecure.azs" | "application/vnd.amazon.ebook" | "application/vnd.americandynamics.acc" | "application/vnd.amiga.ami" | "application/vnd.android.package-archive" | "application/vnd.anser-web-certificate-issue-initiation" | "application/vnd.anser-web-funds-transfer-initiation" | "application/vnd.antix.game-component" | "application/vnd.apple.installer+xml" | "application/vnd.apple.keynote" | "application/vnd.apple.mpegurl" | "application/vnd.apple.numbers" | "application/vnd.apple.pages" | "application/vnd.apple.pkpass" | "application/vnd.aristanetworks.swi" | "application/vnd.astraea-software.iota" | "application/vnd.audiograph" | "application/vnd.autodesk.fbx" | "application/vnd.balsamiq.bmml+xml" | "application/vnd.blueice.multipass" | "application/vnd.bmi" | "application/vnd.businessobjects" | "application/vnd.chemdraw+xml" | "application/vnd.chipnuts.karaoke-mmd" | "application/vnd.cinderella" | "application/vnd.citationstyles.style+xml" | "application/vnd.claymore" | "application/vnd.cloanto.rp9" | "application/vnd.clonk.c4group" | "application/vnd.cluetrust.cartomobile-config" | "application/vnd.cluetrust.cartomobile-config-pkg" | "application/vnd.commonspace" | "application/vnd.contact.cmsg" | "application/vnd.cosmocaller" | "application/vnd.crick.clicker" | "application/vnd.crick.clicker.keyboard" | "application/vnd.crick.clicker.palette" | "application/vnd.crick.clicker.template" | "application/vnd.crick.clicker.wordbank" | "application/vnd.criticaltools.wbs+xml" | "application/vnd.ctc-posml" | "application/vnd.cups-ppd" | "application/vnd.curl.car" | "application/vnd.curl.pcurl" | "application/vnd.dart" | "application/vnd.data-vision.rdz" | "application/vnd.dbf" | "application/vnd.dcmp+xml" | "application/vnd.dece.data" | "application/vnd.dece.ttml+xml" | "application/vnd.dece.unspecified" | "application/vnd.dece.zip" | "application/vnd.denovo.fcselayout-link" | "application/vnd.dna" | "application/vnd.dolby.mlp" | "application/vnd.dpgraph" | "application/vnd.dreamfactory" | "application/vnd.ds-keypoint" | "application/vnd.dvb.ait" | "application/vnd.dvb.service" | "application/vnd.dynageo" | "application/vnd.ecowin.chart" | "application/vnd.enliven" | "application/vnd.epson.esf" | "application/vnd.epson.msf" | "application/vnd.epson.quickanime" | "application/vnd.epson.salt" | "application/vnd.epson.ssf" | "application/vnd.eszigno3+xml" | "application/vnd.ezpix-album" | "application/vnd.ezpix-package" | "application/vnd.fdf" | "application/vnd.fdsn.mseed" | "application/vnd.fdsn.seed" | "application/vnd.flographit" | "application/vnd.fluxtime.clip" | "application/vnd.framemaker" | "application/vnd.frogans.fnc" | "application/vnd.frogans.ltf" | "application/vnd.fsc.weblaunch" | "application/vnd.fujitsu.oasys" | "application/vnd.fujitsu.oasys2" | "application/vnd.fujitsu.oasys3" | "application/vnd.fujitsu.oasysgp" | "application/vnd.fujitsu.oasysprs" | "application/vnd.fujixerox.ddd" | "application/vnd.fujixerox.docuworks" | "application/vnd.fujixerox.docuworks.binder" | "application/vnd.fuzzysheet" | "application/vnd.genomatix.tuxedo" | "application/vnd.geogebra.file" | "application/vnd.geogebra.slides" | "application/vnd.geogebra.tool" | "application/vnd.geometry-explorer" | "application/vnd.geonext" | "application/vnd.geoplan" | "application/vnd.geospace" | "application/vnd.gmx" | "application/vnd.google-apps.document" | "application/vnd.google-apps.drawing" | "application/vnd.google-apps.form" | "application/vnd.google-apps.jam" | "application/vnd.google-apps.map" | "application/vnd.google-apps.presentation" | "application/vnd.google-apps.script" | "application/vnd.google-apps.site" | "application/vnd.google-apps.spreadsheet" | "application/vnd.google-earth.kml+xml" | "application/vnd.google-earth.kmz" | "application/vnd.gov.sk.xmldatacontainer+xml" | "application/vnd.grafeq" | "application/vnd.groove-account" | "application/vnd.groove-help" | "application/vnd.groove-identity-message" | "application/vnd.groove-injector" | "application/vnd.groove-tool-message" | "application/vnd.groove-tool-template" | "application/vnd.groove-vcard" | "application/vnd.hal+xml" | "application/vnd.handheld-entertainment+xml" | "application/vnd.hbci" | "application/vnd.hhe.lesson-player" | "application/vnd.hp-hpgl" | "application/vnd.hp-hpid" | "application/vnd.hp-hps" | "application/vnd.hp-jlyt" | "application/vnd.hp-pcl" | "application/vnd.hp-pclxl" | "application/vnd.hydrostatix.sof-data" | "application/vnd.ibm.minipay" | "application/vnd.ibm.modcap" | "application/vnd.ibm.rights-management" | "application/vnd.ibm.secure-container" | "application/vnd.iccprofile" | "application/vnd.igloader" | "application/vnd.immervision-ivp" | "application/vnd.immervision-ivu" | "application/vnd.insors.igm" | "application/vnd.intercon.formnet" | "application/vnd.intergeo" | "application/vnd.intu.qbo" | "application/vnd.intu.qfx" | "application/vnd.ipunplugged.rcprofile" | "application/vnd.irepository.package+xml" | "application/vnd.is-xpr" | "application/vnd.isac.fcs" | "application/vnd.jam" | "application/vnd.jcp.javame.midlet-rms" | "application/vnd.jisp" | "application/vnd.joost.joda-archive" | "application/vnd.kahootz" | "application/vnd.kde.karbon" | "application/vnd.kde.kchart" | "application/vnd.kde.kformula" | "application/vnd.kde.kivio" | "application/vnd.kde.kontour" | "application/vnd.kde.kpresenter" | "application/vnd.kde.kspread" | "application/vnd.kde.kword" | "application/vnd.kenameaapp" | "application/vnd.kidspiration" | "application/vnd.kinar" | "application/vnd.koan" | "application/vnd.kodak-descriptor" | "application/vnd.las.las+xml" | "application/vnd.llamagraphics.life-balance.desktop" | "application/vnd.llamagraphics.life-balance.exchange+xml" | "application/vnd.lotus-1-2-3" | "application/vnd.lotus-approach" | "application/vnd.lotus-freelance" | "application/vnd.lotus-notes" | "application/vnd.lotus-organizer" | "application/vnd.lotus-screencam" | "application/vnd.lotus-wordpro" | "application/vnd.macports.portpkg" | "application/vnd.mapbox-vector-tile" | "application/vnd.mcd" | "application/vnd.medcalcdata" | "application/vnd.mediastation.cdkey" | "application/vnd.mfer" | "application/vnd.mfmp" | "application/vnd.micrografx.flo" | "application/vnd.micrografx.igx" | "application/vnd.mif" | "application/vnd.mobius.daf" | "application/vnd.mobius.dis" | "application/vnd.mobius.mbk" | "application/vnd.mobius.mqy" | "application/vnd.mobius.msl" | "application/vnd.mobius.plc" | "application/vnd.mobius.txf" | "application/vnd.mophun.application" | "application/vnd.mophun.certificate" | "application/vnd.mozilla.xul+xml" | "application/vnd.ms-artgalry" | "application/vnd.ms-cab-compressed" | "application/vnd.ms-excel" | "application/vnd.ms-excel.addin.macroenabled.12" | "application/vnd.ms-excel.sheet.binary.macroenabled.12" | "application/vnd.ms-excel.sheet.macroenabled.12" | "application/vnd.ms-excel.template.macroenabled.12" | "application/vnd.ms-fontobject" | "application/vnd.ms-htmlhelp" | "application/vnd.ms-ims" | "application/vnd.ms-lrm" | "application/vnd.ms-officetheme" | "application/vnd.ms-outlook" | "application/vnd.ms-pki.seccat" | "application/vnd.ms-pki.stl" | "application/vnd.ms-powerpoint" | "application/vnd.ms-powerpoint.addin.macroenabled.12" | "application/vnd.ms-powerpoint.presentation.macroenabled.12" | "application/vnd.ms-powerpoint.slide.macroenabled.12" | "application/vnd.ms-powerpoint.slideshow.macroenabled.12" | "application/vnd.ms-powerpoint.template.macroenabled.12" | "application/vnd.ms-project" | "application/vnd.ms-visio.viewer" | "application/vnd.ms-word.document.macroenabled.12" | "application/vnd.ms-word.template.macroenabled.12" | "application/vnd.ms-works" | "application/vnd.ms-wpl" | "application/vnd.ms-xpsdocument" | "application/vnd.mseq" | "application/vnd.musician" | "application/vnd.muvee.style" | "application/vnd.mynfc" | "application/vnd.nato.bindingdataobject+xml" | "application/vnd.neurolanguage.nlu" | "application/vnd.nitf" | "application/vnd.noblenet-directory" | "application/vnd.noblenet-sealer" | "application/vnd.noblenet-web" | "application/vnd.nokia.n-gage.ac+xml" | "application/vnd.nokia.n-gage.data" | "application/vnd.nokia.n-gage.symbian.install" | "application/vnd.nokia.radio-preset" | "application/vnd.nokia.radio-presets" | "application/vnd.novadigm.edm" | "application/vnd.novadigm.edx" | "application/vnd.novadigm.ext" | "application/vnd.oasis.opendocument.chart" | "application/vnd.oasis.opendocument.chart-template" | "application/vnd.oasis.opendocument.database" | "application/vnd.oasis.opendocument.formula" | "application/vnd.oasis.opendocument.formula-template" | "application/vnd.oasis.opendocument.graphics" | "application/vnd.oasis.opendocument.graphics-template" | "application/vnd.oasis.opendocument.image" | "application/vnd.oasis.opendocument.image-template" | "application/vnd.oasis.opendocument.presentation" | "application/vnd.oasis.opendocument.presentation-template" | "application/vnd.oasis.opendocument.spreadsheet" | "application/vnd.oasis.opendocument.spreadsheet-template" | "application/vnd.oasis.opendocument.text" | "application/vnd.oasis.opendocument.text-master" | "application/vnd.oasis.opendocument.text-template" | "application/vnd.oasis.opendocument.text-web" | "application/vnd.olpc-sugar" | "application/vnd.oma.dd2+xml" | "application/vnd.openblox.game+xml" | "application/vnd.openofficeorg.extension" | "application/vnd.openstreetmap.data+xml" | "application/vnd.openxmlformats-officedocument.presentationml.presentation" | "application/vnd.openxmlformats-officedocument.presentationml.slide" | "application/vnd.openxmlformats-officedocument.presentationml.slideshow" | "application/vnd.openxmlformats-officedocument.presentationml.template" | "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet" | "application/vnd.openxmlformats-officedocument.spreadsheetml.template" | "application/vnd.openxmlformats-officedocument.wordprocessingml.document" | "application/vnd.openxmlformats-officedocument.wordprocessingml.template" | "application/vnd.osgeo.mapguide.package" | "application/vnd.osgi.dp" | "application/vnd.osgi.subsystem" | "application/vnd.palm" | "application/vnd.pawaafile" | "application/vnd.pg.format" | "application/vnd.pg.osasli" | "application/vnd.picsel" | "application/vnd.pmi.widget" | "application/vnd.pocketlearn" | "application/vnd.powerbuilder6" | "application/vnd.previewsystems.box" | "application/vnd.procrate.brushset" | "application/vnd.procreate.brush" | "application/vnd.procreate.dream" | "application/vnd.proteus.magazine" | "application/vnd.publishare-delta-tree" | "application/vnd.pvi.ptid1" | "application/vnd.pwg-xhtml-print+xml" | "application/vnd.quark.quarkxpress" | "application/vnd.rar" | "application/vnd.realvnc.bed" | "application/vnd.recordare.musicxml" | "application/vnd.recordare.musicxml+xml" | "application/vnd.rig.cryptonote" | "application/vnd.rim.cod" | "application/vnd.rn-realmedia" | "application/vnd.rn-realmedia-vbr" | "application/vnd.route66.link66+xml" | "application/vnd.sailingtracker.track" | "application/vnd.seemail" | "application/vnd.sema" | "application/vnd.semd" | "application/vnd.semf" | "application/vnd.shana.informed.formdata" | "application/vnd.shana.informed.formtemplate" | "application/vnd.shana.informed.interchange" | "application/vnd.shana.informed.package" | "application/vnd.simtech-mindmapper" | "application/vnd.smaf" | "application/vnd.smart.teacher" | "application/vnd.software602.filler.form+xml" | "application/vnd.solent.sdkm+xml" | "application/vnd.spotfire.dxp" | "application/vnd.spotfire.sfs" | "application/vnd.stardivision.calc" | "application/vnd.stardivision.draw" | "application/vnd.stardivision.impress" | "application/vnd.stardivision.math" | "application/vnd.stardivision.writer" | "application/vnd.stardivision.writer-global" | "application/vnd.stepmania.package" | "application/vnd.stepmania.stepchart" | "application/vnd.sun.wadl+xml" | "application/vnd.sun.xml.calc" | "application/vnd.sun.xml.calc.template" | "application/vnd.sun.xml.draw" | "application/vnd.sun.xml.draw.template" | "application/vnd.sun.xml.impress" | "application/vnd.sun.xml.impress.template" | "application/vnd.sun.xml.math" | "application/vnd.sun.xml.writer" | "application/vnd.sun.xml.writer.global" | "application/vnd.sun.xml.writer.template" | "application/vnd.sus-calendar" | "application/vnd.svd" | "application/vnd.symbian.install" | "application/vnd.syncml+xml" | "application/vnd.syncml.dm+wbxml" | "application/vnd.syncml.dm+xml" | "application/vnd.syncml.dmddf+xml" | "application/vnd.tao.intent-module-archive" | "application/vnd.tcpdump.pcap" | "application/vnd.tmobile-livetv" | "application/vnd.trid.tpt" | "application/vnd.triscape.mxs" | "application/vnd.trueapp" | "application/vnd.ufdl" | "application/vnd.uiq.theme" | "application/vnd.umajin" | "application/vnd.unity" | "application/vnd.uoml+xml" | "application/vnd.vcx" | "application/vnd.visio" | "application/vnd.visionary" | "application/vnd.vsf" | "application/vnd.wap.wbxml" | "application/vnd.wap.wmlc" | "application/vnd.wap.wmlscriptc" | "application/vnd.webturbo" | "application/vnd.wolfram.player" | "application/vnd.wordperfect" | "application/vnd.wqd" | "application/vnd.wt.stf" | "application/vnd.xara" | "application/vnd.xfdl" | "application/vnd.yamaha.hv-dic" | "application/vnd.yamaha.hv-script" | "application/vnd.yamaha.hv-voice" | "application/vnd.yamaha.openscoreformat" | "application/vnd.yamaha.openscoreformat.osfpvg+xml" | "application/vnd.yamaha.smaf-audio" | "application/vnd.yamaha.smaf-phrase" | "application/vnd.yellowriver-custom-menu" | "application/vnd.zul" | "application/vnd.zzazz.deck+xml" | "application/x-7z-compressed" | "application/x-abiword" | "application/x-ace-compressed" | "application/x-apple-diskimage" | "application/x-arj" | "application/x-authorware-bin" | "application/x-authorware-map" | "application/x-authorware-seg" | "application/x-bcpio" | "application/x-bdoc" | "application/x-bittorrent" | "application/x-blender" | "application/x-blorb" | "application/x-bzip" | "application/x-bzip2" | "application/x-cbr" | "application/x-cdlink" | "application/x-cfs-compressed" | "application/x-chat" | "application/x-chess-pgn" | "application/x-chrome-extension" | "application/x-cocoa" | "application/x-compressed" | "application/x-conference" | "application/x-cpio" | "application/x-csh" | "application/x-debian-package" | "application/x-dgc-compressed" | "application/x-director" | "application/x-doom" | "application/x-dtbncx+xml" | "application/x-dtbook+xml" | "application/x-dtbresource+xml" | "application/x-dvi" | "application/x-envoy" | "application/x-eva" | "application/x-font-bdf" | "application/x-font-ghostscript" | "application/x-font-linux-psf" | "application/x-font-pcf" | "application/x-font-snf" | "application/x-font-type1" | "application/x-freearc" | "application/x-futuresplash" | "application/x-gca-compressed" | "application/x-glulx" | "application/x-gnumeric" | "application/x-gramps-xml" | "application/x-gtar" | "application/x-hdf" | "application/x-httpd-php" | "application/x-install-instructions" | "application/x-ipynb+json" | "application/x-iso9660-image" | "application/x-iwork-keynote-sffkey" | "application/x-iwork-numbers-sffnumbers" | "application/x-iwork-pages-sffpages" | "application/x-java-archive-diff" | "application/x-java-jnlp-file" | "application/x-keepass2" | "application/x-latex" | "application/x-lua-bytecode" | "application/x-lzh-compressed" | "application/x-makeself" | "application/x-mie" | "application/x-mobipocket-ebook" | "application/x-ms-application" | "application/x-ms-shortcut" | "application/x-ms-wmd" | "application/x-ms-wmz" | "application/x-ms-xbap" | "application/x-msaccess" | "application/x-msbinder" | "application/x-mscardfile" | "application/x-msclip" | "application/x-msdos-program" | "application/x-msdownload" | "application/x-msmediaview" | "application/x-msmetafile" | "application/x-msmoney" | "application/x-mspublisher" | "application/x-msschedule" | "application/x-msterminal" | "application/x-mswrite" | "application/x-netcdf" | "application/x-ns-proxy-autoconfig" | "application/x-nzb" | "application/x-perl" | "application/x-pilot" | "application/x-pkcs12" | "application/x-pkcs7-certificates" | "application/x-pkcs7-certreqresp" | "application/x-rar-compressed" | "application/x-redhat-package-manager" | "application/x-research-info-systems" | "application/x-sea" | "application/x-sh" | "application/x-shar" | "application/x-shockwave-flash" | "application/x-silverlight-app" | "application/x-sql" | "application/x-stuffit" | "application/x-stuffitx" | "application/x-subrip" | "application/x-sv4cpio" | "application/x-sv4crc" | "application/x-t3vm-image" | "application/x-tads" | "application/x-tar" | "application/x-tcl" | "application/x-tex" | "application/x-tex-tfm" | "application/x-texinfo" | "application/x-tgif" | "application/x-ustar" | "application/x-virtualbox-hdd" | "application/x-virtualbox-ova" | "application/x-virtualbox-ovf" | "application/x-virtualbox-vbox" | "application/x-virtualbox-vbox-extpack" | "application/x-virtualbox-vdi" | "application/x-virtualbox-vhd" | "application/x-virtualbox-vmdk" | "application/x-wais-source" | "application/x-web-app-manifest+json" | "application/x-x509-ca-cert" | "application/x-xfig" | "application/x-xliff+xml" | "application/x-xpinstall" | "application/x-xz" | "application/x-zip-compressed" | "application/x-zmachine" | "audio/vnd.dece.audio" | "audio/vnd.digital-winds" | "audio/vnd.dra" | "audio/vnd.dts" | "audio/vnd.dts.hd" | "audio/vnd.lucent.voice" | "audio/vnd.ms-playready.media.pya" | "audio/vnd.nuera.ecelp4800" | "audio/vnd.nuera.ecelp7470" | "audio/vnd.nuera.ecelp9600" | "audio/vnd.rip" | "audio/x-aac" | "audio/x-aiff" | "audio/x-caf" | "audio/x-flac" | "audio/x-m4a" | "audio/x-matroska" | "audio/x-mpegurl" | "audio/x-ms-wax" | "audio/x-ms-wma" | "audio/x-pn-realaudio" | "audio/x-pn-realaudio-plugin" | "audio/x-realaudio" | "audio/x-wav" | "chemical/x-cdx" | "chemical/x-cif" | "chemical/x-cmdf" | "chemical/x-cml" | "chemical/x-csml" | "chemical/x-xyz" | "image/prs.btif" | "image/prs.pti" | "image/vnd.adobe.photoshop" | "image/vnd.airzip.accelerator.azv" | "image/vnd.blockfact.facti" | "image/vnd.dece.graphic" | "image/vnd.djvu" | "image/vnd.dvb.subtitle" | "image/vnd.dwg" | "image/vnd.dxf" | "image/vnd.fastbidsheet" | "image/vnd.fpx" | "image/vnd.fst" | "image/vnd.fujixerox.edmics-mmr" | "image/vnd.fujixerox.edmics-rlc" | "image/vnd.microsoft.icon" | "image/vnd.ms-dds" | "image/vnd.ms-modi" | "image/vnd.ms-photo" | "image/vnd.net-fpx" | "image/vnd.pco.b16" | "image/vnd.tencent.tap" | "image/vnd.valve.source.texture" | "image/vnd.wap.wbmp" | "image/vnd.xiff" | "image/vnd.zbrush.pcx" | "image/x-3ds" | "image/x-adobe-dng" | "image/x-cmu-raster" | "image/x-cmx" | "image/x-freehand" | "image/x-icon" | "image/x-jng" | "image/x-mrsid-image" | "image/x-ms-bmp" | "image/x-pcx" | "image/x-pict" | "image/x-portable-anymap" | "image/x-portable-bitmap" | "image/x-portable-graymap" | "image/x-portable-pixmap" | "image/x-rgb" | "image/x-tga" | "image/x-xbitmap" | "image/x-xpixmap" | "image/x-xwindowdump" | "message/vnd.wfa.wsc" | "model/vnd.bary" | "model/vnd.cld" | "model/vnd.collada+xml" | "model/vnd.dwf" | "model/vnd.gdl" | "model/vnd.gtw" | "model/vnd.mts" | "model/vnd.opengex" | "model/vnd.parasolid.transmit.binary" | "model/vnd.parasolid.transmit.text" | "model/vnd.pytha.pyox" | "model/vnd.sap.vds" | "model/vnd.usda" | "model/vnd.usdz+zip" | "model/vnd.valve.source.compiled-map" | "model/vnd.vtu" | "text/prs.lines.tag" | "text/vnd.curl" | "text/vnd.curl.dcurl" | "text/vnd.curl.mcurl" | "text/vnd.curl.scurl" | "text/vnd.dvb.subtitle" | "text/vnd.familysearch.gedcom" | "text/vnd.fly" | "text/vnd.fmi.flexstor" | "text/vnd.graphviz" | "text/vnd.in3d.3dml" | "text/vnd.in3d.spot" | "text/vnd.sun.j2me.app-descriptor" | "text/vnd.wap.wml" | "text/vnd.wap.wmlscript" | "text/x-asm" | "text/x-c" | "text/x-component" | "text/x-fortran" | "text/x-handlebars-template" | "text/x-java-source" | "text/x-lua" | "text/x-markdown" | "text/x-nfo" | "text/x-opml" | "text/x-org" | "text/x-pascal" | "text/x-processing" | "text/x-sass" | "text/x-scss" | "text/x-setext" | "text/x-sfv" | "text/x-suse-ymp" | "text/x-uuencode" | "text/x-vcalendar" | "text/x-vcard" | "video/vnd.dece.hd" | "video/vnd.dece.mobile" | "video/vnd.dece.pd" | "video/vnd.dece.sd" | "video/vnd.dece.video" | "video/vnd.dvb.file" | "video/vnd.fvt" | "video/vnd.mpegurl" | "video/vnd.ms-playready.media.pyv" | "video/vnd.uvvu.mp4" | "video/vnd.vivo" | "video/x-f4v" | "video/x-fli" | "video/x-flv" | "video/x-m4v" | "video/x-matroska" | "video/x-mng" | "video/x-ms-asf" | "video/x-ms-vob" | "video/x-ms-wm" | "video/x-ms-wmv" | "video/x-ms-wmx" | "video/x-ms-wvx" | "video/x-msvideo" | "video/x-sgi-movie" | "video/x-smv" | "x-conference/x-cooltalk">;
export { mimeType };
